name: 'BundleTool Runner'
description: 'Installs Google BundleTool'
author: 'Evgenij Razumov (enniel)'
inputs:
  version:
    description: 'Bundletool version'
    required: false
    default: "1.8.1"
  working-directory:
    description: 'A custom working directory'
    required: false
  command:
    description: 'Bundletool command'
    required: false
  bundle:
    description: 'Specifies the path to the app bundle you built using Android Studio'
    required: false
  output:
    description: 'Specifies the name of the output `.apks` file, which contains all the APK artifacts for your app.'
    required: false
  overwrite:
    description: "Include this flag if you want to overwrite any existing output file with the same path you specify using the output option. If you don't include this flag and the output file already exists, you get a build error."
    required: false
  aapt2:
    description: "Specifies a custom path to AAPT2. By default, bundletool includes its own version of AAPT2."
    required: false
  ks:
    description: "Specifies the path to the deployment keystore used to sign the APKs. This flag is optional. If you don't include it, bundletool attempts to sign your APKs with a debug signing key."
    required: false
  ks-pass:
    description: "Specifies the password for the signing key. If you’re specifying a password in plain text, qualify it with pass:. If you’re passing the path to a file that contains the password, qualify it with file:. If this password is identical to the one for the keystore itself, you can omit this flag."
    required: false
  ks-key-alias:
    description: 'Specifies the alias of the signing key you want to use.'
    required: false
  connected-device:
    description: 'Instructs bundletool to build APKs that target the configuration of a connected device. If you don’t include this flag, bundletool generates APKs for all device configurations your app supports.'
    required: false
  device-id:
    description: 'If you have more than one connected device, use this flag to specify the serial ID of the device to which you want to deploy your app.'
    required: false
  device-spec:
    description: 'Use this flag to provide a path to a .json file that specifies the device configuration you want to target.'
    required: false
  mode:
    description: "Set the mode to universal if you want bundletool to build only a single APK that includes all of your app's code and resources such that the APK is compatible with all device configurations your app supports."
    required: false
  local-testing:
    description: "Use this flag to enable your app bundle for local testing. Local testing allows for quick, iterative testing cycles without the need to upload to Google Play servers."
    required: false
runs:
  using: 'node12'
  main: 'lib/index.js'
