name: "Test"

on: [push, pull_request]

jobs:
  without-options:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      
      - name: install bundletool
        uses: ./

  custom-version:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v1
      
      - name: install bundletool
        uses: ./
        with:
          version: "1.7.1"

  build-apks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: setup android sdk
        uses: android-actions/setup-android@v2

      - name: list android devices
        run: "$ANDROID_SDK_ROOT/tools/bin/avdmanager list"

      - name: download image
        run: "$ANDROID_SDK_ROOT/tools/bin/sdkmanager --install 'system-images;android-29;default;x86_64'"

      - name: create avd
        run: "echo 'no' | $ANDROID_SDK_ROOT/tools/bin/avdmanager create avd -n test -k 'system-images;android-29;default;x86_64'"

      - name: start emulator
        run: "$ANDROID_SDK_ROOT/emulator/emulator -avd test -no-window -noaudio -no-boot-anim -camera-back none &>/dev/null &"

      - name: build apks
        uses: ./
        with:
          command: "build-apks"
          bundle: "./test-app/app-release.aab"
          output: "./test-app/app-release.apks"
          ks: "./test-app/release.keystore"
          ks-pass: "pass:android"
          ks-key-alias: "androiddebugkey"
          overwrite: true

      - name: install apks
        uses: ./
        with:
          command: "install-apks"
          apks: "./test-app/app-release.apks"
